version: 2
jobs:
jobs:
  build:
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: 'Build docker images'
          command: bundle exec rake build
      - run:
          name: 'Push to docker hub'
          command: |
            docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
            bundle exec rake push
workflows:
  version: 2
  build:
    jobs:
      - build
