version: 2
jobs:
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.0
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: 'Install dependencies'
          command: |
            gem install bundler
            bundle install
      - run:
          name: 'Build docker images'
          command: bundle exec rake build
      - run:
          name: 'Run tests'
          command: bundle exec rake test
      - run:
          name: 'Push to docker hub'
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            bundle exec rake push
workflows:
  version: 2
  build_test_and_push:
    jobs:
      - build
